spring:
  profiles:
     active: dev
---
server:
    prot: 8201
spring:
  profiles : dev
  application:
    name: config-client
        
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
    prot: 8202
spring:
  profiles : prd
  application:
    name: config-client
        
eureka:
  client:
    service-url:
      defaultZone: http://eureka-prs.com:7001/eureka/
